import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "../contextAPI/Context";
import Header from "../components/Header";
import Footer from "../components/Footer";
import LoginModal from "../components/LoginModal";
import MobileSlideMenu from "../components/MobileSlideMenu";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "R.F.Daboo Centra site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ContextProvider>
          <Header />
          <main className="flex-1">
            {children}
          </main>
          <Footer />
          <LoginModal />
          <MobileSlideMenu />
        </ContextProvider>
      </body>
    </html>
  );
}
